apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-complete-timed
spec:
  delay:
    durationFrom:
      expressionFrom: '.metadata.annotations["kwok.x-k8s.io/duration"]'
  next:
    statusSubresource: status
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      containerStatuses:
      {{ range $index, $item := .spec.containers }}
      {{ $origin := index $root.status.containerStatuses $index }}
      - image: {{ $item.image | Quote }}
        name: {{ $item.name | Quote }}
        ready: false
        restartCount: 0
        started: false
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ $now | Quote }}
            reason: Completed
            startedAt: {{ $now | Quote }}
      {{ end }}
      phase: Succeeded
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: .metadata.deletionTimestamp
      operator: DoesNotExist
    - key: .status.phase
      operator: In
      values:
      - Running
    - key: '.metadata.ownerReferences.[].kind'
      operator: In
      values:
      - Job
    # Only match pods that have a duration annotation
    - key: '.metadata.annotations["kwok.x-k8s.io/duration"]'
      operator: Exists
    # Exclude pods marked for manual completion
    - key: '.metadata.labels["kwok.x-k8s.io/complete"]'
      operator: DoesNotExist
  weight: 1
